// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Processos.Infra.Contexto;

namespace Processos.Infra.Migrations
{
    [DbContext(typeof(ContextoProcessos))]
    [Migration("20190807225951_CriacaoInicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Processos.Dominio.Entidades.Etapa", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EtapaEntradaIdentificador");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<Guid?>("ProcessoIdentificador");

                    b.Property<int>("Tipo");

                    b.Property<int>("X");

                    b.Property<int>("Y");

                    b.HasKey("Identificador");

                    b.HasIndex("EtapaEntradaIdentificador");

                    b.HasIndex("ProcessoIdentificador");

                    b.ToTable("Etapa");
                });

            modelBuilder.Entity("Processos.Dominio.Entidades.Parada", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid?>("EtapaIdentificador");

                    b.Property<int>("Turno");

                    b.HasKey("Identificador");

                    b.HasIndex("EtapaIdentificador");

                    b.ToTable("Parada");
                });

            modelBuilder.Entity("Processos.Dominio.Entidades.Problema", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<Guid?>("EtapaIdentificador");

                    b.Property<int>("Turno");

                    b.HasKey("Identificador");

                    b.HasIndex("EtapaIdentificador");

                    b.ToTable("Problema");
                });

            modelBuilder.Entity("Processos.Dominio.Entidades.Processo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Identificador");

                    b.ToTable("Processo");
                });

            modelBuilder.Entity("Processos.Dominio.Entidades.Etapa", b =>
                {
                    b.HasOne("Processos.Dominio.Entidades.Etapa", "EtapaEntrada")
                        .WithMany("EtapasSaida")
                        .HasForeignKey("EtapaEntradaIdentificador");

                    b.HasOne("Processos.Dominio.Entidades.Processo", "Processo")
                        .WithMany("Etapas")
                        .HasForeignKey("ProcessoIdentificador");
                });

            modelBuilder.Entity("Processos.Dominio.Entidades.Parada", b =>
                {
                    b.HasOne("Processos.Dominio.Entidades.Etapa", "Etapa")
                        .WithMany("Paradas")
                        .HasForeignKey("EtapaIdentificador");
                });

            modelBuilder.Entity("Processos.Dominio.Entidades.Problema", b =>
                {
                    b.HasOne("Processos.Dominio.Entidades.Etapa", "Etapa")
                        .WithMany("Problemas")
                        .HasForeignKey("EtapaIdentificador");
                });
#pragma warning restore 612, 618
        }
    }
}
